checksumBehavior: update

nmMode: classic

logFilters:
  - code: YN0060
    pattern: "*react is listed by your project with version 18.3.1 (p4b86af)*"
    level: discard
  - code: YN0086
    pattern: "*Some peer dependencies are incorrectly met by your project*"
    level: discard
  - code: YN0086
    pattern: "*Some peer dependencies are incorrectly met by dependencies*"
    level: discard

npmScopes:
  fortawesome:
    npmAuthToken: "${FONTAWESOME_NPM_AUTH_TOKEN}"
    npmRegistryServer: "https://npm.fontawesome.com"
